Add Jest as the javascript test framework
CCI-MOC/GUI-Frontend pull request #14
Opened 2017-03-17 21:26 UTC by xuhang57

Add jest as the javascript framework for GIJI.

https://facebook.github.io/jest/docs/tutorial-react.html#content

After pulling this PR,

try type `npm test` under the `/opt/dev/troposphere` directory and `/opt/env/troposphere` environment.

2017-03-20 15:17 UTC, rob-baron requested changes
Travis CI needs to work with this.

2017-03-20 15:59 UTC, robbaronbu commented
I don't like the notion of snapshot testing as it captures snapshots of serializable structures, then uses those structures in a similar manner to mock data on django.  It is better to not have this feature, this way we are sure that we are testing with the current version of the server.

2017-03-20 17:20 UTC, rob-baron requested changes
I was noticing that tests does not seem be run in the logs of travis.  Perhaps you need to add the line:

"npm run test" 

to the script section of the .travis.yml file.

2017-03-20 17:36 UTC, xuhang57 commented
The test won't pass because it is checking all 11 test scripts that they originally had. And those scripts are written with using another framework. I was going to delete them but I think we should keep them since they could serve as good examples about writing the unit test. 

So, I think we should do a manual check first and start writing the testing script asap.

2017-03-20 18:52 UTC, robbaronbu commented
If you want to keep the previous unit tests however, they are temporarily broken, you can skip them. This is typically done using skip as documented here (https://facebook.github.io/jest/docs/api.html).  This means we run the non-broken tests every time travis ci runs.

2017-03-20 18:54 UTC, rob-baron requested changes
If you want to keep the previous unit tests however, they are temporarily broken, you can skip them. This is typically done using skip as documented here (https://facebook.github.io/jest/docs/api.html). This means we run the non-broken tests every time travis ci runs.

You can also have jest ignore the 11 files or rename them so that jest doesn't find them.

2017-03-21 18:05 UTC, rob-baron approved these changes

2017-03-24 16:52 UTC, knikolla requested changes

2017-03-24 16:52 UTC, knikolla commented on test/components/projects/common/projectListHeader.spec.js
> +        title = "3" + "Projects"
Remove the "3".

2017-03-24 17:12 UTC, xuhang57 commented
@knikolla  Thanks and removed

2017-03-24 17:18 UTC, knikolla approved these changes

2017-03-24 20:51 UTC, merged